#!/bin/sh


# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done


/usr/sbin/inetd &
/usr/sbin/httpd -h /mnt/www/html &
/usr/sbin/telnetd -l /bin/sh
/usr/bin/madplay -q /etc/start.mp3 &
echo "Welcome to SK-iMX233 development board!" > /dev/tty1
